/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tulipa.engine;

import javax.swing.JFrame;
import javax.swing.JLabel;

public class App {
    public String getGreeting() {
        return "Olá mundo!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        JFrame janela = new JFrame("Tulipa Engine");

        JLabel rotulo = new JLabel("teste da tulipa");

        janela.add(rotulo);

        janela.setSize(300, 200);

        janela.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        janela.setVisible(true);
    }
}
